# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI — manage PRs, pipelines, branches, and more"
  homepage "https://github.com/payfacto/bb"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/bb/releases/download/v0.3.1/bb_darwin_amd64.tar.gz"
      sha256 "558e74dd84d3cf209017897fc5104c42ecb2c8d8165b459a9474cce92af67d12"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/bb/releases/download/v0.3.1/bb_darwin_arm64.tar.gz"
      sha256 "09b1d733178bff6b7b61cded1c008ad81d0ba73f46c56ed1bcc4aa33a3ba20bb"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.3.1/bb_linux_amd64.tar.gz"
      sha256 "65029227cff5b10102877dc99f091cbe0ddae826a19c65e3905f8ddcc9536cdb"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.3.1/bb_linux_arm64.tar.gz"
      sha256 "6e2fbab20c38025cc0814e59dd33eed6565c1206e11948c86a90d2aeac0239ee"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--help"
  end
end
