# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI — manage PRs, pipelines, branches, and more"
  homepage "https://github.com/payfacto/bb"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/bb/releases/download/v0.2.0/bb_darwin_amd64.tar.gz"
      sha256 "fc3c8f6f31b8dd646aebbb03847ad1ae0d7044c407825e003d27cf33f5cd8c03"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/bb/releases/download/v0.2.0/bb_darwin_arm64.tar.gz"
      sha256 "a70483ac0bfcd5dc0c517f4e8d0e575586c09496757f65249991fb500f863fd5"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.2.0/bb_linux_amd64.tar.gz"
      sha256 "84a1563f523973ecb7591d179aab5ad757fb8dbb658710d52e5c8d63b599362d"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.2.0/bb_linux_arm64.tar.gz"
      sha256 "698c21eabc687a191d8ba56651cf862d5823d74821825232a853f694856eccdc"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--help"
  end
end
