# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsprof < Formula
  desc "Pick an AWS profile to log in as, from a list of available profiles"
  homepage "https://github.com/payfacto/awsprof-cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.2/awsprof_darwin_amd64.tar.gz"
      sha256 "36176d3278f8848e29dfb791b1c6a1662585935046045b9c0cc680c6e34fe100"

      define_method(:install) do
        bin.install "awsprof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.2/awsprof_darwin_arm64.tar.gz"
      sha256 "75d9a96e12ff5080acd5f58d69552e901ceceabf01742a637e430f3d6bf2f6db"

      define_method(:install) do
        bin.install "awsprof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.2/awsprof_linux_amd64.tar.gz"
      sha256 "4d725aa34014f165bf38cd6fb379a448fbf2b88fa9d46addcb99d8b83a56f8c8"
      define_method(:install) do
        bin.install "awsprof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.2/awsprof_linux_arm64.tar.gz"
      sha256 "87a87e013ea1612cd32bb20fd9809a5d2b04489f0ee4bbad9e0d3800edab149a"
      define_method(:install) do
        bin.install "awsprof"
      end
    end
  end

  test do
    system "#{bin}/awsprof", "--help"
  end
end
