# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsprof < Formula
  desc "Pick an AWS profile to log in as, from a list of available profiles"
  homepage "https://github.com/payfacto/awsprof-cli"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.0/awsprof_darwin_amd64.tar.gz"
      sha256 "0c1f3a98f1042986345c00f2593f2399b4287473a9a73d65bae5ed7971374ba5"

      define_method(:install) do
        bin.install "awsprof"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.0/awsprof_darwin_arm64.tar.gz"
      sha256 "3f07695bedde49c9bedbc10c4ac294fe939ca1cff9e515a6afead3e76b2f1f7e"

      define_method(:install) do
        bin.install "awsprof"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.0/awsprof_linux_amd64.tar.gz"
      sha256 "4487801d9abe1603b5b5825044521b5fb454097ee4627dcbf5780a670b9039fe"
      define_method(:install) do
        bin.install "awsprof"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/awsprof-cli/releases/download/v0.1.0/awsprof_linux_arm64.tar.gz"
      sha256 "7eaf35bcc4eed039436adf9dc5e89a0e83a645b247d7d4a32b223802fbc708e0"
      define_method(:install) do
        bin.install "awsprof"
      end
    end
  end

  test do
    system "#{bin}/awsprof", "--help"
  end
end
