# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI — manage PRs, pipelines, branches, and more"
  homepage "https://github.com/payfacto/bb"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/bb/releases/download/v0.12.0/bb_darwin_amd64.tar.gz"
      sha256 "a44f15d80685346fd20bcf3580cb5a7bcd48163b5dbb9995c76bfb45486c2b77"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/bb/releases/download/v0.12.0/bb_darwin_arm64.tar.gz"
      sha256 "c37206d62d32ed9ee5b0cf804f72df8e5041520b68a74a924465c7c8e8360e6c"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.12.0/bb_linux_amd64.tar.gz"
      sha256 "db07b832613054bb3ab9015b1f64d14896ab33b8208792e1d86f0474ac1bdef4"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.12.0/bb_linux_arm64.tar.gz"
      sha256 "9df23bf916c7c3b2831f1c1821dd3edccac381b36e574c38fd75e392ef644265"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--help"
  end
end
