# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Bitbucket Cloud CLI — manage PRs, pipelines, branches, and more"
  homepage "https://github.com/payfacto/bb"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/bb/releases/download/v0.5.0/bb_darwin_amd64.tar.gz"
      sha256 "453581a60d9ee20290b275416ec757a5c90b8f3061f06f34fc83bce4524c6864"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/bb/releases/download/v0.5.0/bb_darwin_arm64.tar.gz"
      sha256 "afd1ccd98885dedfc403f7a78c5de9000bb33070e9d81871c354f5a8e5d0c570"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.5.0/bb_linux_amd64.tar.gz"
      sha256 "03cc8796035f7629a78995a73b95ba7c51a0a3836488cf466adcfbf3d44e0fad"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/bb/releases/download/v0.5.0/bb_linux_arm64.tar.gz"
      sha256 "12cc7d87443db014dbe4aed4e4f3753856adaca5084ff43545ba7eff269e9328"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--help"
  end
end
