# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaade < Formula
  desc "Yaade CLI - manage collections, requests, environments, and more"
  homepage "https://github.com/payfacto/cli-yaade"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.0/yaade_darwin_amd64.tar.gz"
      sha256 "5f8c6de6e63b9c6748ad350ae80686948790e5c7f72268c44bf1a53e3168f3dd"

      define_method(:install) do
        bin.install "yaade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.0/yaade_darwin_arm64.tar.gz"
      sha256 "de50aae306c9932dc03bc57fe59d0fad255b6a8c431a3d900dd5d33c60a8c284"

      define_method(:install) do
        bin.install "yaade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.0/yaade_linux_amd64.tar.gz"
      sha256 "7e8e2e9fe35dec0469aa862531c93f0d7a2059ab3e35d2133d5a8514b6b55a7c"
      define_method(:install) do
        bin.install "yaade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.0/yaade_linux_arm64.tar.gz"
      sha256 "740b2f884c5a7ccede602de5fac8e1a810bfba424b949603baed3322fc99e85b"
      define_method(:install) do
        bin.install "yaade"
      end
    end
  end

  test do
    system "#{bin}/yaade", "--help"
  end
end
