# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yaade < Formula
  desc "Yaade CLI - manage collections, requests, environments, and more"
  homepage "https://github.com/payfacto/cli-yaade"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.1/yaade_darwin_amd64.tar.gz"
      sha256 "8e4d6bccaf100f0679822fa134c1149c97b13285088a5d34669f196203ccaffd"

      define_method(:install) do
        bin.install "yaade"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.1/yaade_darwin_arm64.tar.gz"
      sha256 "d6d5e694a4aff7e5a1f16fc15aca0db833eaf213e8d33d43643c9b484d775112"

      define_method(:install) do
        bin.install "yaade"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.1/yaade_linux_amd64.tar.gz"
      sha256 "324eff3e3fc5edf2db83484b5c0c8d73f5edf25959a6967bf7e96feb9265eb8e"
      define_method(:install) do
        bin.install "yaade"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/payfacto/cli-yaade/releases/download/v0.1.1/yaade_linux_arm64.tar.gz"
      sha256 "ea8ed2b6cd0a62b1e8eefd9c9702d899f2c94bec3fe8fb2d4d4f7e47e61c3b2a"
      define_method(:install) do
        bin.install "yaade"
      end
    end
  end

  test do
    system "#{bin}/yaade", "--help"
  end
end
